include hyde.conf

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# remap to open new kitty tab in the same directory (default is home dir)
# map ctrl+shift+t            new_tab_with_cwd

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
# sync_to_monitor no
# wayland_enable_ime no

# for custom font size
font_size        12.0
window_padding_width 0


# ─── Layouts ─────────────────────────────
enabled_layouts splits,grid,tall,stack,vertical,horizontal,fat
# Default layout will be the first one: splits




# ─── Tab Management ──────────────────────
map ctrl+tab               next_tab
map ctrl+shift+tab         previous_tab
map ctrl+t                 new_tab
map ctrl+w                 close_tab

# ─── Window Management ───────────────────
map ctrl+n                 new_window

# ─── Split Windows ───────────────────────
map ctrl+shift+right launch --location=vsplit
map ctrl+shift+down  launch --location=hsplit
map ctrl+shift+left  launch --location=vsplit
map ctrl+shift+up    launch --location=hsplit

# ─── Split Size ───────────────────
map ctrl+alt+right resize_window narrower
map ctrl+alt+left resize_window wider
map ctrl+alt+up resize_window taller
map ctrl+alt+down resize_window shorter

mouse_map ctrl+button1 press_window_action resize_window

# ─── Search function ─────────────────
map ctrl+f show_scrollback



# ─── Focus Movement ──────────────────────
map ctrl+left  neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up    neighboring_window up
map ctrl+down  neighboring_window down

# ─── Clipboard ───────────────────────────
map ctrl+shift+c           copy_to_clipboard
map ctrl+shift+v           paste_from_clipboard

# Set background opacity (0 = fully transparent, 1 = fully opaque)
background_opacity 0.85
blur: 5


