# Wallust Zsh Template
# Automatically generated by Wallust

# Define colors for Zsh plugins
export WALLUST_BACKGROUND="{{background}}"
export WALLUST_FOREGROUND="{{foreground}}"
export WALLUST_ACCENT="{{color4}}"

# Autosuggestions - use accent color instead of potentially invisible gray
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg={{color4}}"

# Syntax highlighting overrides (examples)
# typeset -A ZSH_HIGHLIGHT_STYLES
# ZSH_HIGHLIGHT_STYLES[command]="fg={{color4}},bold"
# ZSH_HIGHLIGHT_STYLES[alias]="fg={{color4}}"
