# Wallust v4 configuration for MyArch

backend = "fastresize"
palette = "salience"

[templates]
swayosd = { template = 'swayosd.css', target = '~/.config/swayosd/style.css' }
hyprlock = { template = 'hyprlock.conf', target = '~/.config/hypr/hyprlock-colors.conf' }
wlogout = { template = 'wlogout.css', target = '~/.config/wlogout/style.css' }
