general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # Lock before suspending
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn screen on when waking up
}

# 1. Lock the screen after 5 minutes (300 seconds)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 2. Put the computer to sleep right after locking (e.g., 330 seconds)
listener {
    timeout = 330
    on-timeout = systemctl suspend
}
