$background = rgb(010103)
$foreground = rgb(A5FFFF)
$color0 = rgb(020103)
$color1 = rgb(0E021C)
$color2 = rgb(0E021C)
$color3 = rgb(0D2616)
$color4 = rgb(142433)
$color5 = rgb(4F7FA4)
$color6 = rgb(91EFF9)
$color7 = rgb(A0FEFF)
$color8 = rgb(49A9B2)
$color9 = rgb(0E021C)
$color10 = rgb(0E021C)
$color11 = rgb(0D2616)
$color12 = rgb(142433)
$color13 = rgb(4F7FA4)
$color14 = rgb(91EFF9)
$color15 = rgb(C7F6F7)
