# ═══════════════════════════════════════════════════════════════════════════
# VARIABLES & ENVIRONMENT
# ═══════════════════════════════════════════════════════════════════════════

# ── Programs ────────────────────────────────────────────────────────────────
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun -theme ~/.config/rofi/themes/launcher.rasi


# ── Environment Variables ──────────────────────────────────────────────────
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Theming & Platform Variables
env = GTK_THEME,Adwaita:dark
env = XCURSOR_THEME,Adwaita
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORM,wayland;xcb
env = ADW_DISABLE_PORTAL,1

# SSH socket for keyring
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/keyring/ssh
