# Wallust Zsh Template
# Automatically generated by Wallust

# Define colors for Zsh plugins
export WALLUST_BACKGROUND="#020101"
export WALLUST_FOREGROUND="#D2D077"
export WALLUST_ACCENT="#562C16"

# Autosuggestions - use accent color instead of potentially invisible gray
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#562C16"

# Syntax highlighting overrides (examples)
# typeset -A ZSH_HIGHLIGHT_STYLES
# ZSH_HIGHLIGHT_STYLES[command]="fg=#562C16,bold"
# ZSH_HIGHLIGHT_STYLES[alias]="fg=#562C16"
